/*This is a normal rock, paper & scissors game where player 
enter r for rock, p for paper and s for scissors and at the end 
of the game score of player displays the number of wins by the computer.*/
#include<stdio.h>
#include<stdlib.h>
#include<time.h>
#include<conio.h>
int main(){
    int cho,numb; 
    do{
        char player,computer; 
        int c=0;
        system("COLOR 02");
        //Menu of the Game
        printf("\n\t\t\t-----MENU-----\n"); 
        printf("\t\t\t1. Let's Play\n");
        printf("\t\t\t2. Exit\n");
        printf("\t\t\tEnter Your Choice Here :");
        scanf("%d",&cho);
        switch(cho){
            case 1:
            do{
            printf("\n\t\t\tPress e to End the Game!!!"); //To End the game
            // Logic to generate Random Choices by the Computer
            srand(time(0));
            numb=rand()%100+1;
            if(numb>33 && numb<66){ 
                computer='r';
            }
            else if(numb>66){
                computer='p';
            }
            else{
                computer='s';
            }
            fflush(stdin); // to clear new line character from buffer
            //Game Instructions
            printf("\n\t\t\t--Welcome Player--");
            printf("\n\t\t\tRock : r && Paper : p && Scissors : s");
            printf("\n\t\t\tEnter Your Choice : ");
            scanf("%c",&player);
            printf("\n\t\t\tYou : %c",player);
            printf("\n\t\t\tComputer : %c",computer);
            //Logic of the game
            if(player==computer)
            {
                printf("\n\t\t\tDraw (Same Choice)");
            }
            if(player=='r' && computer=='p'){
                printf("\n\t\t\tYou Lose!!");
            }
            else if(player=='p' && computer=='r'){
                printf("\n\t\t\tYou Win!!");
                c++;
            }
            if(player=='s' && computer=='r'){
                printf("\n\t\t\tYou Lose!!");
            }
            else if(player=='r' && computer=='s'){
                printf("\n\t\t\tYou Win!!");
                c++;
            }
            if(player=='p' && computer=='s'){
                printf("\n\t\t\tYou Lose!!");
            }
            else if(player=='s' && computer=='p'){
                printf("\n\t\t\tYou Win!!");
                c++;
            }
            }while(player!='e');
            printf("\n\t\t\tYour Score : %d",c); //Final Score generated by counter variable
            break;

            case 2:
            printf("\t\t\t****Thanks For Visiting****\n"); //Exiting
            break;

            default:
            printf("\t\t\tWrong Choice_Plzz Enter Again\n");
            break;
        }
    }while(cho!=2); 
    system("pause"); //to hold the screen 
    getchar();
    return 0;
}
